[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["shigaki daichi <d-shigaki@pro-seeds.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"